plugins {
    id 'dev.architectury.loom'
    id 'architectury-plugin'
    id 'maven-publish'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_name
}

repositories {
    maven { url "https://maven.terraformersmc.com" }
}

dependencies {
    minecraft "net.minecraft:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:intermediary:${project.minecraft_version}"

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation fabricApi.module("fabric-resource-loader-v0", project.fabric_api_version)
    modImplementation fabricApi.module("fabric-key-mapping-api-v1", project.fabric_api_version)

    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    modRuntimeOnly fabricApi.module("fabric-screen-api-v1", project.fabric_api_version)
    modRuntimeOnly fabricApi.module("fabric-lifecycle-events-v1", project.fabric_api_version)
}

loom {
    accessWidenerPath = file("src/main/resources/languagereload.classtweaker")
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = "UTF-8"
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE")
}
