# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod properties
mod_version = 2.0.0-26.1.2
maven_group = com.gaura.mining_and_placing_animations
archives_name = mining_and_placing_animations
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.155.2+26.1.2
sodium_version = mc26.1.2-0.9.1-fabric
iris_version = 1.11.3+26.1