pluginManagement {
    repositories {
        maven { url 'https://maven.architectury.dev/' }
        maven { url 'https://maven.fabricmc.net/' }
        maven { url 'https://libraries.minecraft.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'mining_and_placing_animations'
include('common', 'fabric')
